### ISSUE TITLE
multihash/multiformat message format

### ISSUE THREAD

**Issue by willwarren89** [0xProject/ZEIPs#10]
## Summary
Add a layer of abstraction within 0x message format that removes dependence on specific hashing / cryptographic functions.

## Motivation
0x protocol v1.0 relies upon use of the keccak256 hashing function and the secp256k1 elliptic curve for ECDSA. Ethereum will soon support new hashing functions (Blake2b) and cryptographic primitives (ed25519, Lamport, EC used in secure hardware enclaves, zk-snarks, threshold signatures, ...) that could allow for interesting new functionality within 0x protocol if supported. [Multihash/multiformat](https://github.com/multiformats/multihash) support in 0x message format is the first step that we can take towards generalizing and future-proofing 0x protocol.

## Specification
...

## Rationale
...

## Notes
...

**Comment by whyrusleeping** [comment]
👋 If you guys have any questions about multiformats feel free to let me or anyone on the ipfs team know

**Comment by Recmo** [comment]
@whyrusleeping I noticed that at the moment there is no multiformat for cryptographic signatures. Is this correct?

I'm currently working on generalized signature verification for version 2 ([PR](https://github.com/0xProject/0x.js/blob/fdc6cde7bb73ee1027811f5ebf23aae799694aab/packages/contracts/src/contracts/current/protocol/Exchange/MixinSignatureValidator.sol#L28)). The current implementation is similar to a multiformat, but rather Ethereum specific.

**Comment by willwarren89** [comment]
A reference worth looking at: [IPFS Multihash for Solidity](https://github.com/saurfang/ipfs-multihash-on-solidity).

**Comment by whyrusleeping** [comment]
@Recmo That is correct, there is currently no multiformat for signatures. Its something thats needed as we move towards more interesting peer to peer apps. 

cc @lgierth who has most of the context on multiformats research
