### ISSUE TITLE
Do not double check signatures of previously filled/cancelled orders

### ISSUE THREAD

**Issue by abandeali1** [0xProject/ZEIPs#15]
## Summary
Currently, if you fill (or partially fill) an order that was already filled or cancelled, the Exchange contract will re-evaluate the signature of the order. This ZEIP would remove the need to verify the signature of an already partially filled or cancelled order.

## Motivation
An order that has already been partially filled or cancelled always implies that the order has been approved by the maker. Skipping signature verification would save at least 3000 gas with no additional downside.

## Specification
```
    if (filled[orderHash] == 0 && cancelled[orderHash] == 0) {
        require(isValidSignature(...);
    }
```

**Comment by AusIV** [comment]
This would be incompatible with https://github.com/0xProject/ZEIPs/issues/3

As the same hash could have different signatures for different fee configurations.
