### ISSUE TITLE
Support ERC1155: MultiToken Standard

### ISSUE THREAD

**Issue by dekz** [0xProject/ZEIPs#24]
## Summary

The current `AssetProxy` contracts allow an order to buy or sell ERC20 and ERC721 assets. This proposes a new `AssetProxy` to enable the exchange of assets managed by an [ERC1155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1155.md) contract, which provides a standard interface for managing a collection of fungible and non-fungible assets. 

## Motivation

Existing token standards (ERC20, ERC721) require a separate smart contract to manage each asset. ERC1155 defines an interface for a contract that manages a collection of assets. Applications range from game assets to deposit and staking contracts.

### Requirements

* The `ERC1155Proxy` should be able to transfer any number of fungible/non-fungible ERC1155 assets
* The `ERC1155Proxy` should only be callable by approved senders (the exchange contract and multi asset proxy)
* The `ERC1155Proxy` should support partial fills: the amount of each asset transferred should be proportional to the amount that the order is filled (see Fill Scenarios section below).

### Asset Data Encoding

The ERC1155Proxy should expect data to be encoded using the following function signature:
```
// 0xa7cb5fb7
ERC1155Assets(address,uint256[],uint256[],bytes)
```
Arguments:

* address       - The address of the ERC1155 contract
* uint256[]  - A collection of asset ids to transfer
* uint256[]  - The value of each each asset to transfer
* bytes           - Callback data forwarded to the receiver, if the receiver is a contract

### Fill Scenarios

Fills operate in a similar way to the [MultiAssetProxy](https://github.com/0xProject/ZEIPs/issues/23). Values encoded in the asset data are multiplied by the amount to compute the total quantity of an asset to transfer.
```
# Scenario 1: Maker wants to sell 2000 units of AssetA and 4000 units of AssetB.
#             Both assets are fungible and partial fills are allowed.
order.makerAssetAmount = 2000
order.makerAssetData.ids = [AssetA, AssetB]
order.makerAssetData.values = [1, 2]

# Scenario 2: Maker wants to sell 2000 units of AssetA and 4000 units of AssetB.
#             Both assets are fungible but partial fills are *not* allowed.
order.makerAssetAmount = 1
order.makerAssetData.ids = [AssetA, AssetB]
order.makerAssetData.values = [2000, 4000]

# Scenario 3: Maker wants to sell 2000 units of AssetA and a non-fungible AssetC.
#             Because AssetC is non-fungible partial fills are *not* allowed.
order.makerAssetAmount = 1
order.makerAssetData.ids = [AssetA, AssetC]
order.makerAssetData.values = [2000, 1]
```
Note that partial fills of non-fungible assets should be prohibited by the maker by setting the amount to 1. The proxy cannot distinguish between fungible and non-fungible assets, so it cannot force partial fills to fail in this scenario. If the amount is _not_ set to 1 and an asset is non-fungible then the behavior depends on the implementation of the ERC1155 contract. 

### Architecture

The `ERC1155Proxy` inherits `MixinAuthorizable`. Like the `ERC20Proxy` and `ERC721Proxy`, this contract must be registered with the `Exchange` and `MultiAssetProxy`, which in turn must be authorized to call `ERC1155Proxy.transferFrom`. 

When an order's asset data specifies the `ERC1155Proxy`, the chain of calls looks like:

1. Call to `Exchange` contract
2. `Exchange` calls `ERC1155Proxy`
3. `ERC1155Proxy` calls `batchTransferFrom` on the destination ERC1155 contract

OR

1. Call to `Exchange` contract
2. `Exchange` calls `MultiAssetProxy`
3. `MultiAssetProxy` decodes the 1155 asset data and calls `ERC1155Proxy`
4. `ERC1155Proxy` calls `batchTransferFrom` on the destination ERC1155 contract

### Reference Implementation

Below is the reference implementation for the `ERC1155Proxy` contract. The optimized version is under development and can be found in the 0x codebase [here](https://github.com/0xProject/0x-monorepo/blob/development/contracts/asset-proxy/contracts/src/ERC1155Proxy.sol).
```
pragma solidity 0.5.5;
pragma experimental ABIEncoderV2;

import "@0x/contracts-utils/contracts/src/LibBytes.sol";
import "@0x/contracts-utils/contracts/src/SafeMath.sol";
import "@0x/contracts-erc1155/contracts/src/interfaces/IERC1155.sol";
import "./MixinAuthorizable.sol";


contract ERC1155Proxy is
    MixinAuthorizable,
    SafeMath
{
    using LibBytes for bytes;

    // Id of this proxy.
    bytes4 constant internal PROXY_ID = bytes4(keccak256("ERC1155Assets(address,uint256[],uint256[],bytes)"));

    /// @dev Transfers assets. Either succeeds or throws.
    /// @param assetData Byte array encoded for the respective asset proxy.
    /// @param from Address to transfer asset from.
    /// @param to Address to transfer asset to.
    /// @param amount Amount of asset to transfer.
    function transferFrom(
        bytes calldata assetData,
        address from,
        address to,
        uint256 amount
    )
        external
        onlyAuthorized
    {
        // decode asset data
        bytes memory assetDataWithoutProxyId = assetData.slice(4, assetData.length);
        (
            address erc1155Contract,
            uint256[] memory ids,
            uint256[] memory values,
            bytes memory data
        ) = abi.decode(
            assetDataWithoutProxyId,
            (address,uint256[],uint256[],bytes)
        );

        // scale values
        for(uint i = 0; i != values.length; ++i) {
            values[i] = safeMul(values[i], amount);
        }

        // execute transfer
        IERC1155(erc1155Contract).safeBatchTransferFrom(
            from,
            to,
            ids,
            values,
            data
        );
    }

    /// @dev Gets the proxy id associated with the proxy address.
    /// @return Proxy id.
    function getProxyId()
        external
        pure
        returns (bytes4)
    {
        return PROXY_ID;
    }
}
```
## Issues

* The EIP155 proposal has not yet been ratified and is subject to change. I recommend we hold off on third-party audits until the EIP has been finalized.
* The receiver can implement a custom callback, which means that stateful assets can be tampered with during a trade. This is a known issue when exchanging some ERC721 tokens and more generally with contract-fillable liquidity.
* It would be more ideal to prevent partial fills of non-fungible assets within the proxy, rather than relying on the Maker to set the `makerAssetAmount` or `takerAssetAmount` to 1. That said, this is the same trust model used by existing proxies, like the `MultiAssetProxy` which has the same issue.

**Comment by redsquirrel** [comment]
> ~ERC115~ has support for single transfer and batch transfer.

ERC1155

**Comment by PhABC** [comment]
I made this a few months ago to test 0x with 1155 : 

https://gist.github.com/PhABC/fdbdcc90865f404628e68d4af47d62f8

(extension is `.js` to have some syntax highlight)
