### ISSUE TITLE
OrdewWatcher could keep track of the amount used.

### ISSUE THREAD

**Issue by valkyriaivan** [0xProject/ZEIPs#25]
## Summary
OrdewWatcher could keep track of the amount the user has on orders, simplifying the implementation of a system to track user used balance.

## Motivation
The watchers part of the protocol is quite small and, for me, incomplete. While it brings support for a lot of use cases, it is hard to keep track of the used balance. It can be done counting the amounts when the user create, cancel or fill orders. But it adds a lot of complexity when the user decrease his balance below the total of the cumulative. While the OrderStateInvalid gives a lot of error types that help you decide what to do, OrderStateValid provide no help to understand what changed in the order/orders.

## Specification
This could be done adding it to the order watcher or creating another watcher like the expiration.
It could:

Keep track of the amount for the given user and address:
`amountWatcher.getUsedBalance(USER_ADD, TOKEN_ADD)`
return: int

Get the stats for the given user.
`amountWatcher.getStatsUser(USER_ADD)`
return: { orderCount: int}

An also, the most important. Just like the order watcher, a subscribe function to get relevant state from all the orders. For example, if the user balance is lower than the used balance, it returns the orders that "can't" be filled anymore, starting from the oldest.
`amountWatcher.subscribe(callback: OnAmountStateChangeCallback)`
return: { invalidOrders: [ orderHashes ], *changedOrders: [ relevantState{} ] }

Where the invalidOrders are the oldest orders that added up, they exceed the new balance. 
*The changedOrders is maybe optional, while it could be usefull in case the order could still be partially filled. And the relevantState could be { orderHash, remainingAmount }.

## Rationale
It could help developers implement orderWatcher on their API because ad of right now, a user with 1000 tokens can create 10 orders for 1000 and if the relayer is keeping track of the used balance, he couldn't create more. But if the user sends 9000 tokens away, all 10 orders are still fillable and could make a mess when multiple of those orders are filled at the same with with batchFillOrdersAsync().
So, with this implementation, the API could track the amountWatcher and the moment the user changes balance, the API can delete the oldest 9 orders and keep just 1. It's not the same as cancelling those, but maybe if can hide the orders until the user has balance again.

## Notes
As note I want to share one test I did that made me think of these. I had 2 orders for 5000 tokens each. When I gave 7500 tokens to my other wallet, my API detected a change in the orders with the orderWatcher and tried to "change" the amount left to fill to the front end. But then I realized both orders changed it's amount to 2500, making a total of 5000 tokens. While with these implemented I could detect that one has to be deleted or hide and the other one change the amount to 2500.

**Comment by abandeali1** [comment]
Hey @valkyriaivan, can you repost this an an issue in https://github.com/0xProject/0x-monorepo? This repo is for protocol level improvements and standards, rather than issues with the associated tooling.
