### ISSUE TITLE
Make more Exchange functions public

### ISSUE THREAD

**Issue by feuGeneA** [0xProject/ZEIPs#45]
## Summary

Change a number of `Exchange` methods from `private` visibility to `public`.

## Motivation

To reduce the barrier to entry for new development environments (new languages, etc), we will expose a number of on-chain helper and verification functions. With these functions, any language that can call into the EVM can get started with 0x quickly, without having to reimplement common logic.

## Specification

The following functions will be made public:

* `getOrderHash`
* `assertValidFill`
* `calculateMatchedFillResults`
* `isValidWalletSignature`
* `isValidValidatorSignature`
* `hashZeroExTransaction`
* `getTransactionHash`

**Comment by dorothy-zbornak** [comment]
Now in review in [#1885](https://github.com/0xProject/0x-monorepo/pull/1885).
