### ISSUE TITLE
On-chain order generation by smart contracts

### ISSUE THREAD

**Issue by abandeali1** [0xProject/ZEIPs#7]
## Summary
Up until now, the focus of discussion has been on how to generate an order on behalf of a contract off-chain. However, there is a definite value in allowing a contract to generate an order on-chain (e.g a DAO voting on the creation of an order).

## Motivation
Currently, there is no way for smart contracts to generate orders (see issue #1 ).

## Specification
The following additions can be added to the Exchange contract:

```
mapping(bytes32 => bool) public isOrderApproved;

function approveOrder(
    address[5] orderAddresses,
    uint[6] orderValues)
    public
    returns (bool)
{
    require(orderAddresses[0] == msg.sender);
    bytes32 orderHash = getOrderHash(orderAddresses, orderValues);
    isOrderApproved[orderHash] = true;
    return true;
}
````
Then, when verifying an order signature, we check:

```
require(isValidSignature(...) || isOrderApproved[order.orderHash]);
```

## Rationale
This allows any contract to approve an order on-chain in place of a signature.

**Comment by retotrinkler** [comment]
Hi, whats the eta for this?

**Comment by fabioberger** [comment]
Instead of keeping a separate mapping, we could also designate `2^256-1` as a special case and add the approved orderHash to the `filled` map. Upon the first partial fill, this value would be overwritten. 

Any entry in the `filled` mapping is known to either have a valid signature or be approved. 

This isn't a great separation of concern, however it does reduce the gas cost of the initial fill:

- Contract approving an order -> 20k
- First order partial fill -> 5k (instead of 20k without this optimization)

**Comment by abandeali1** [comment]
Although that would be an efficiency, it's a bit inconsistent with how we've been special casing `2^256-1`. I also think that long term, there's more value in this: https://github.com/0xProject/ZEIPs/issues/11

**Comment by abandeali1** [comment]
@retotrinkler this will be included in the next version, but we are still deciding on the other features that will be added.

**Comment by izqui** [comment]
What is the status of this? I'm considering doing an EIP for an ecosystem-wide smart contract where contracts can 'sign a hash'. The interface looks like this:

```
contract ISignHolder {
    /**
    * @notice Returns whether `who` ever sign `hash`. Even if she cancelled, this will return true.
    */
    function signed(address who, bytes32 hash) public view returns (bool);

    /**
     * @notice Returns if `who` signed `hash` and hasnt cancelled the signature.
     */
    function isSigned(address who, bytes32 hash) public view returns (bool);
}
```

and this would be an initial implementation:

```
contract SignHolder is ISignHolder {
    mapping (address => mapping (bytes32 => bool)) signatures;
    mapping (address => mapping (bytes32 => bool)) cancels;

    function sign(bytes32 hash) external { signatures[msg.sender][hash] = true; }
    function cancel(bytes32 hash) external { cancels[msg.sender][hash] = true; }

    function signed(address who, bytes32 hash) public view returns (bool) {
        return signatures[who][hash];
    }

    function isSigned(address who, bytes32 hash) public view returns (bool) {
        return signatures[who][hash] && !cancels[who][hash];
    }
}
```

Then from contracts like the 0x Exchange you would directly check whether a contract has signed a hash, as an alternative for ecrecover when the code size of an address is greater than 0.

```
contract EIPSign {
    ISignHolder constant SIGN_HOLDER = ISignHolder(0x1234); // TODO: Address

    function check(address who, bytes32 hash) internal view returns (bool) {
        if (msg.sender == who) return true; // Implicit authorization by sender
        return SIGN_HOLDER.signed(who, hash);
    }
}
```

I feel like this is better than making a specific implementation just for 0x. In terms of gas costs, it would be slightly more expensive than just checking in the contract, as you need to add the cost for a `CALL` to the `SignHolder`. However I think this is better, specially thinking that account abstraction is not that far away.

**Comment by abandeali1** [comment]
Interesting. What do you think is the benefit of standardizing this? It seems to me that signatures are typically used for application/protocol specific messages, so putting them in a global scope might not be that useful. The other problems I see are:

- Users have no incentive to sign messages this way at an increased cost. For example, If this contract is deployed in parallel to a 0x version, it would be always be cheaper to use the 0x version for validating a 0x order.
- `cancel` adds a race condition that seems very difficult, if not impossible, to remove. I'd prefer removing it altogether.

**Comment by izqui** [comment]
What I think is important is having a global way for contracts to signal they approve something, the equivalent as signing an arbitrary payload with a private key. The type of payloads being signed would defer depending on the protocol, in the same way that ECDSA signatures work the same independently of the data being signed. 

Another more limited advantage of keeping it generic, is that data could be 'signed' before knowing on what application/protocol it is relevant for. As well as signing data that isn't relevant to any protocol, like expressing conformity to an agreement by 'signing' its hash.

Regarding costs, it would be as cheap for the order maker, taking the order would add around 700 gas (IMO not a deal-breaker for its benefits).

**Comment by abandeali1** [comment]
700 gas doesn't seem like a big deal, but that does make the maker's order slightly less attractive to a taker (and in general we want to cut out any extra gas from transactions that happen frequently). 

I do see value in standardizing this, but my preference would be to first check the internal 0x mapping and fall back to the global signature contract. This would mean that the global contract can have false negatives, but I think that's going to be hard to avoid anyways.

**Comment by izqui** [comment]
I think that is a good compromise :) If 'order signatures' can't be cancelled on the 0x mapping nor the global signing contract, then just seeing that a the hash is present in either of those could be enough to know that the order has been approved. You could even make it a public function such as `checkContractOrderSignature(bytes32 orderHash, address signer) view returns (bool)` that checks both and once it returns true, you know that will be true for ever.

**Comment by silentinfotechllp** [comment]
@abandeali1 Is there any reference implementation for this strategy where we can define the approveOrder, isValidSignature and isOrderApproved?

**Comment by Recmo** [comment]
@izqui The [current PR](https://github.com/0xProject/0x.js/pull/376) for signature generalization in not `0x` specific and could be re-used by other project, or even used as a standard. Please check the [`MixinSignatureValidator` contract](https://github.com/0xProject/0x.js/blob/feature/contracts/module-refactors/packages/contracts/src/contracts/current/protocol/Exchange/MixinSignatureValidator.sol).
