### ISSUE TITLE
Add `chainId` or `network` field to 0x message format

### ISSUE THREAD

**Issue by willwarren89** [0xProject/ZEIPs#8]
## Summary
Add a field to the [0x message format](https://github.com/0xProject/contracts#message-format) that specifies the target `chainID`.

## Motivation
In 0x protocol v1.0, the order message format includes an `exchangeContractAddress` field, indicating the Ethereum address of `Exchange.sol` which accepts and processes 0x orders. However, while `exchangeContractAddress` implicitly identifies the target chain, it does not account for blockchain forks that can result in parallel versions of the 0x protocol smart contracts. Further, in the multi-blockchain/shard/[plasma](https://plasma.io/) future, it will reduce ambiguity if the 0x message format explicitly includes an ID that corresponds to the specific chain in which an order is to be settled.

## Specification
Each order is a data packet containing order parameters and an associated signature. Order parameters are concatenated and hashed to 32 bytes via the Keccak SHA3 function. The order originator signs the order hash with their private key to produce an ECDSA signature.

Name | Data Type | Description
--- | --- | ---
chainId | `uint256` | ID number associated with a specific EVM blockchain.
exchangeContractAddress | `address` | Address of the Exchange contract. This address will change each time the protocol is updated.
maker | `address` | Address originating the order.
taker | `address` | Address permitted to fill the order (optional).
makerToken | `address` | Address of an ERC20 Token contract.
takerToken | `address` | Address of an ERC20 Token contract.
makerTokenAmount | `uint256` | Total units of makerToken offered by maker.
takerTokenAmount | `uint256` | Total units of takerToken requested by maker.
expirationTimestampInSec | `uint256` | Time at which the order expires (seconds since unix epoch).
salt | `uint256` | Arbitrary number that allows for uniqueness of the order's Keccak SHA3 hash.
feeRecipient | `address` | Address that recieves transaction fees (optional).
makerFee | `uint256` | Total units of ZRX paid to feeRecipient by maker.
takerFee | `uint256` | Total units of ZRX paid to feeRecipient by taker.
v | `uint8` | ECDSA signature of the above arguments.
r | `bytes32` | ECDSA signature of the above arguments.
s | `bytes32` | ECDSA signature of the above arguments.

## Notes
There are various ways of differentiating between target chains. Options include using a [registry that maps a specific chain to a `uint` ID number](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) or using a plaintext tag of the chain name. The end goal is to reduce ambiguity.

**Comment by AntonioJuliano** [comment]
This seems like a good idea in general

I assume the chainId would be a state variable stored on the exchange contract, and then you use that state variable while checking signatures. In the case of a fork the 0x exchange contract and its associated storage/code would be the same on both chains, so how would the two versions of the exchange contract tell which chain they are on? I suppose you could allow the owner to update the state variable on the forked chain, but that would have some delay, and the owner would have to update the state chainId variable on each forked chain

**Comment by Recmo** [comment]
In addition to being implicitly stored in the `exchangeContractAddress`, the chain id is also explicitly stored in the `v` parameter (`chain_id = (v - 35) / 2`).
