### ISSUE TITLE
Add Support for BSC

### ISSUE THREAD

**Issue by gabririgo** [0xProject/ZEIPs#81]
## Summary
Support Binance Smart Chain networks

## Type: 
OPERATIONS

## Motivation
Binance Smart Chain is a Proof-of-Authority Ethereum chain with higher throughput and lower cost than Ethereum main chain. For some applications where the Ethereum main chain is not vital, it can provide a good alternative. In particular, NFT markets would benefit and derivatives matching relayers. 

## Specification
0x core team should deploy the 0x protocol pipeline on networks Mainnet(ChainID 56) and Testnet(ChainID 97) and support the two networks in the 0x libraries and 0x mesh. As the 0x rewards system makes use of the ZRX token for weighting market makers' fee rebate distribution, a ZRX token is required on the Binance Smart Chain. This could be an issue, as no trustless ERC20-BRP20 bridge exists.

## Rationale (if a suggestion is proposed)
By being the first DEX protocol on Binance Smart Chain, 0x would establish leadership on the chain with minimal effort, as the 0x protocol is already available on 3 other Ethereum chains other than the Ethereum main network.

## Implementation

TBD

## Designated team: UFG

UFG

## Sponsor (for CORE type only): UFG

UFG

## Notes
A ZRX token on Binance Smart Chain is required (this is a note against the proposal).

**Comment by mintcloud** [comment]
Deployed contracts on BSC

https://blog.0xproject.com/0x-protocol-is-now-live-on-binance-smart-chain-d9329fc974ad
